services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ${ROOT_DATA_DIR}/monitoreo/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      - TZ=${TIMEZONE}
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  node_exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - "9100:9100"
    environment:
      - TZ=${TIMEZONE}
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - TZ=${TIMEZONE}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - prometheus
    restart: unless-stopped
