services:
  web:
    image: redis/redisinsight:latest
    container_name: redis
    user: root
    volumes:
      - ${ROOT_DATA_DIR}/redis/data:/data
    environment:
      - TZ=${TIMEZONE}
      - RI_LOG_LEVEL=debug
    restart: unless-stopped
    networks:
      - traefik_net
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
      # TRAEFIK
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`${REDIS_DOMAIN}`)"
      - "traefik.http.routers.redis.entrypoints=websecure"
      - "traefik.http.routers.redis.tls.certresolver=cloudflare"
      - "traefik.http.services.redis.loadbalancer.server.port=5540"

networks:
  traefik_net:
    external: true