# stacks/excalidraw.yml

- name: Ejecutar Docker Compose
  community.docker.docker_compose_v2:
    project_src: ../docker/excalidraw
    state: present
  environment:
    TIMEZONE: "{{ TIMEZONE }}"
    EXCALIDRAW_DOMAIN: "{{ EXCALIDRAW_DOMAIN }}"
  register: result

- name: Mostrar resultado
  include_tasks: _show_result.yml
