# stacks/syncthing.yml

- name: Crear directorios para volúmenes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ROOT_DATA_DIR }}/syncthing/config"

- name: Ejecutar Docker Compose
  community.docker.docker_compose_v2:
    project_src: ../docker/syncthing
    state: present
  environment:
    ROOT_DATA_DIR: "{{ ROOT_DATA_DIR }}"
    TIMEZONE: "{{ TIMEZONE }}"
    SYNCTHING_DOMAIN: "{{ SYNCTHING_DOMAIN }}"
    SYNCTHING_DATA_DIR: "{{ SYNCTHING_DATA_DIR }}"
  register: result

- name: Mostrar resultado
  include_tasks: _show_result.yml
