services:
  portainer:
    image: portainer/portainer-ee
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8880:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT_DATA_DIR}/portainer/data:/data
    environment:
      - TZ=${TIMEZONE}
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true