services:
  db:
    image: postgres:16.4
    container_name: gitea-db
    hostname: gitea-db
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ${ROOT_DATA_DIR}/gitea/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${GITEA_DB}
      - POSTGRES_USER=${GITEA_USER}
      - POSTGRES_PASSWORD=${GITEA_PASSWORD}
    restart: unless-stopped
    networks:
      - traefik_net
  web:
    image: gitea/gitea:latest
    container_name: gitea
    hostname: gitea
    privileged: true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
    ports:
      - 3052:3000
      - 2222:22
    volumes:
      - ${ROOT_DATA_DIR}/gitea/data:/data
      - /etc/TZ:/etc/TZ:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=${GITEA_DB}
      - GITEA__database__USER=${GITEA_USER}
      - GITEA__database__PASSWD=${GITEA_PASSWORD}
      - GITEA__migrations__ALLOWED_DOMAINS=*
      - GITEA__webhook__ALLOWED_HOST_LIST=*
      - ROOT_URL=${GITEA_URL}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`${GITEA_DOMAIN}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=cloudflare"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    networks:
      - traefik_net
    depends_on:
      - db

networks:
  traefik_net:
    external: true