services:
  db:
    image: postgres:16.4
    container_name: gitea-db
    hostname: gitea-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ${ROOT_DATA_DIR}/gitea/db:/var/lib/postgresql/data:rw
      - ${ROOT_DATA_DIR}/gitea/init:/docker-entrypoint-initdb.d
      - ${ROOT_DATA_DIR}/gitea/backups:/backup
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${GITEA_DB}
      - POSTGRES_USER=${GITEA_USER}
      - POSTGRES_PASSWORD=${GITEA_PASSWORD}
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - traefik_net
  web:
    image: gitea/gitea:latest
    container_name: gitea
    hostname: gitea
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
    ports:
    - "2222:22"
    volumes:
      - ${ROOT_DATA_DIR}/gitea/data:/data
      - /etc/TZ:/etc/TZ:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # https://docs.gitea.io/en-us/config-cheat-sheet
      ## DEFAULT
      ROOT_URL: ${GITEA_URL}
      GITEA__log__LEVEL: debug
      GITEA____APP_NAME: "Gitea: homelab server"
      GITEA____RUN_MODE: "dev"
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__server__SSH_PORT: 2222
      ## DATABASE
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea-db:5432
      GITEA__database__NAME: ${GITEA_DB}
      GITEA__database__USER: ${GITEA_USER}
      GITEA__database__PASSWD: ${GITEA_PASSWORD}
      ## MAILER
      GITEA__mailer__ENABLED: "true"
      GITEA__mailer__SMTP_ADDR: ${GITEA_EMAIL_ADDR}
      GITEA__mailer__SMTP_PORT: ${GITEA_EMAIL_PORT}
      GITEA__mailer__FROM: ${GITEA_EMAIL_FROM}
      GITEA__mailer__USER: ${GITEA_EMAIL_USER}
      GITEA__mailer__PASSWD: ${GITEA_EMAIL_PASSWORD}
      ## HOSTS
      GITEA__migrations__ALLOWED_DOMAINS: "*"
      GITEA__webhook__ALLOWED_HOST_LIST: "*"
    restart: unless-stopped
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
      # TRAEFIK
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`${GITEA_DOMAIN}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=cloudflare"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    networks:
      - traefik_net
    depends_on:
      - db

networks:
  traefik_net:
    external: true
