services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT_DATA_DIR}/homarr/configs:/app/data/configs
      - ${ROOT_DATA_DIR}/homarr/icons:/app/public/icons
      - ${ROOT_DATA_DIR}/homarr/data:/data
    environment:
      - TZ=${TIMEZONE}
    ports:
      - '7575:7575'