services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ROOT_DATA_DIR}/homarr/appdata:/appdata
    environment:
      - TZ=${TIMEZONE}
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_KEY}
    healthcheck:
      disable: true
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
      # TRAEFIK
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`${HOMARR_DOMAIN}`)"
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.routers.homarr.tls.certresolver=cloudflare"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
      # GLANCE
      - "glance.name=homarr"
      - "glance.icon=di:homarr"
      - "glance.url=https://${HOMARR_DOMAIN}"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true