services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    security_opt:
      - no-new-privileges=true
    volumes:
      - ${ROOT_DATA_DIR}/watchtower/log:/var/log/watchtower
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DOCKER_API_VERSION: ${DOCKER_API_VERSION}
      # FLAGS
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      # SCHEDULE
      WATCHTOWER_SCHEDULE: "0 0 1 * * 6"
      WATCHTOWER_TIMEOUT: 30s
      # DEBUGGING
      WATCHTOWER_LOG_FORMAT: "pretty"
      WATCHTOWER_LOG_LEVEL: "debug"
      # NOTIFICATIONS
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${WATCHTOWER_EMAIL_FROM}
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${WATCHTOWER_EMAIL_TO}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: ${WATCHTOWER_EMAIL_SERVER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY: "false"
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${WATCHTOWER_EMAIL_USER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${WATCHTOWER_EMAIL_PASSWORD}
    restart: unless-stopped