# GENERALES
ROOT_DATA_DIR:
TIMEZONE:
DOCKER_API_VERSION:

# PORTAINER
PORTAINER_DOMAIN:

# GITEA
GITEA_DB:
GITEA_USER:
GITEA_PASSWORD:
GITEA_URL:
GITEA_DOMAIN:
GITEA_EMAIL_ADDR:
GITEA_EMAIL_PORT:
GITEA_EMAIL_FROM:
GITEA_EMAIL_USER:
GITEA_EMAIL_PASSWORD:

# WATCHTOWER
WATCHTOWER_EMAIL_FROM:
WATCHTOWER_EMAIL_TO:
WATCHTOWER_EMAIL_SERVER:
WATCHTOWER_EMAIL_USER:
WATCHTOWER_EMAIL_PASSWORD:

# TRAEFIK
TRAEFIK_CLOUDFLARE_DNS_API_TOKEN:
TRAEFIK_DOMAIN:
TRAEFIK_CASAOS_DOMAIN:
TRAEFIK_CASAOS_SERVICE:

# MONITOREO
GRAFANA_ADMIN_USER:
GRAFANA_ADMIN_PASSWORD:
GRAFANA_DOMAIN:
PROMETHEUS_DOMAIN: