# GENERALES
ANSIBLE_USER:
ROOT_DATA_DIR:
TIMEZONE:
DOCKER_API_VERSION:

# DOMAINS
TRAEFIK_DOMAIN:
GITEA_DOMAIN:
PORTAINER_DOMAIN:
GRAFANA_DOMAIN:
PROMETHEUS_DOMAIN:
HOMARR_DOMAIN:
NAVIDROME_DOMAIN:
CASAOS_DOMAIN:
ARTIFACTORY_DOMAIN:
CLOUDBEAVER_DOMAIN:
REDIS_DOMAIN:
UPTIMEKUMA_DOMAIN:
COOLIFY_DOMAIN:
JENKINS_DOMAIN:

# GITEA
GITEA_DB:
GITEA_USER:
GITEA_PASSWORD:
GITEA_URL:
GITEA_EMAIL_ADDR:
GITEA_EMAIL_PORT:
GITEA_EMAIL_FROM:
GITEA_EMAIL_USER:
GITEA_EMAIL_PASSWORD:

# WATCHTOWER
WATCHTOWER_EMAIL_FROM:
WATCHTOWER_EMAIL_TO:
WATCHTOWER_EMAIL_SERVER:
WATCHTOWER_EMAIL_USER:
WATCHTOWER_EMAIL_PASSWORD:

# TRAEFIK
TRAEFIK_CLOUDFLARE_DNS_API_TOKEN:
TRAEFIK_CASAOS_SERVICE:
TRAEFIK_REDIS_SERVICE:
TRAEFIK_COOLIFY_SERVICE:
TRAEFIK_MAIL_CERT:

# MONITOREO
GRAFANA_ADMIN_USER:
GRAFANA_ADMIN_PASSWORD:

# ARTIFACTORY
ARTIFACTORY_DOCKER_REGISTRY:
ARTIFACTORY_VERSION:
ARTIFACTORY_JF_ROUTER_ENTRYPOINTS_EXTERNALPORT:
ARTIFACTORY_DB_USER:
ARTIFACTORY_DB_PASSWORD: