services:
  web:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    volumes:
      - ${ROOT_DATA_DIR}/cloudbeaver:/opt/cloudbeaver/workspace
    environment:
      - TZ=${TIMEZONE}
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
      # TRAEFIK
      - "traefik.enable=true"
      - "traefik.http.routers.cloudbeaver.rule=Host(`${CLOUDBEAVER_DOMAIN}`)"
      - "traefik.http.routers.cloudbeaver.entrypoints=websecure"
      - "traefik.http.routers.cloudbeaver.tls.certresolver=cloudflare"
      - "traefik.http.services.cloudbeaver.loadbalancer.server.port=8978"
    networks:
      - traefik_net
    restart: unless-stopped

networks:
  traefik_net:
    external: true