services:
  web:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - ${ROOT_DATA_DIR}/cloudbeaver:/opt/cloudbeaver/workspace
    environment:
      - TZ=${TIMEZONE}
    restart: unless-stopped