version: "3.9"

services:
  web:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - 8978:8978
    volumes:
      - ${BASE_PATH}/cloudbeaver:/opt/cloudbeaver/workspace
    environment:
      - TZ=America/Santiago
    restart: unless-stopped