http:
  routers:
    casa:
      rule: 'Host(`{{ env "CASAOS_DOMAIN" }}`)'
      entryPoints:
        - websecure
      service: casa
      tls:
        certResolver: cloudflare
    redis:
      rule: 'Host(`{{ env "REDIS_DOMAIN" }}`)'
      entryPoints:
        - websecure
      service: redis
      tls:
        certResolver: cloudflare
    coolify:
      rule: 'Host(`{{ env "COOLIFY_DOMAIN" }}`)'
      entryPoints:
        - websecure
      service: coolify
      tls:
        certResolver: cloudflare

  services:
    casa:
      loadBalancer:
        servers:
          - url: '{{ env "TRAEFIK_CASAOS_SERVICE" }}'
        passHostHeader: true
    redis:
      loadBalancer:
        servers:
          - url: '{{ env "TRAEFIK_REDIS_SERVICE" }}'
        passHostHeader: true
    coolify:
      loadBalancer:
        servers:
          - url: '{{ env "TRAEFIK_COOLIFY_SERVICE" }}'
        passHostHeader: true