global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
http:
  routers:
    casaos:
      rule: "Host(`${CASAOS_DOMAIN}`)"
      entryPoints:
        - websecure
      service: casaos
      tls:
        certResolver: cloudflare
  services:
    casaos:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:5000"