---
- name: Desplegar contenedores en lab
  hosts: localhost
  tasks:
    - name: Crear red Docker traefik_net
      docker_network:
        name: traefik_net
        state: present
    - name: Ejecutar playbook de Traefik
      include_tasks: stacks/traefik-proxy.yml
    - name: Ejecutar playbook de Gitea
      include_tasks: stacks/gitea.yml
    - name: Ejecutar playbook de Portainer
      include_tasks: stacks/portainer.yml
    - name: Ejecutar playbook de Watchtower
      include_tasks: stacks/watchtower.yml