---
- name: Desplegar contenedores en lab
  hosts: localhost
  tasks:
    - name: Crear red Docker traefik_net
      docker_network:
        name: traefik_net
        state: present
    - name: Detener servicios con Docker Compose en múltiples carpetas
      shell: "docker-compose -f {{ item }}/docker-compose.yml down"
      loop:
        - "../docker/traefik"
        - "../docker/portainer"
        - "../docker/watchtower"
        - "../docker/gitea"
      args:
        chdir: "{{ item }}"
      tags:
        - docker_compose_down
    - name: Ejecutar playbook de Traefik
      include_tasks: stacks/traefik-proxy.yml
    - name: Ejecutar playbook de Portainer
      include_tasks: stacks/portainer.yml
    - name: Ejecutar playbook de Watchtower
      include_tasks: stacks/watchtower.yml
    - name: Ejecutar playbook de Gitea
      include_tasks: stacks/gitea.yml