---
- name: Desplegar contenedores en lab principal
  hosts: localhost
  vars:
    disabled_stacks:
      - dev/artifactory
      - dev/cloudbeaver
      - dev/gitea
      - dev/jenkins
      - monitoring/monitoreo
      - media/navidrome
      - dashboard/homarr
      - data/redis
    stacks:
      - infra/traefik-proxy
      - infra/watchtower
      - monitoring/uptimekuma
      - dashboard/glance
      - dashboard/portainer
      - data/syncthing
      - data/valkey
      - media/transmission
      - dev/excalidraw
      - tools/microbin

  tasks:
    - name: Agregar al grupo sudoers
      import_tasks: "stacks/docker.yml"
      tags:
        - docker
        - raspberry
        - linux-vm

    - name: Setup inicial
      import_tasks: "stacks/config.yml"
      tags:
        - config
        - raspberry
        - linux-vm

    - name: Agregar clave pública SSH
      import_tasks: "stacks/ssh.yml"
      tags:
        - ssh
        - raspberry

    - name: Montar disco M.2
      become: yes
      import_tasks: "stacks/m2.yml"
      tags:
        - m2
        - raspberry

    - name: Instalar CasaOS
      become: yes
      import_tasks: "stacks/casaos.yml"
      tags:
        - casaos
        - raspberry

    # Esta task siempre debe ser la última del bloque de init
    # ya que reinicia el servicio y es necesario para que los cambios anteriores tengan efecto
    - name: Habilitar cgroups de memoria para RAM tracking
      become: yes
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: yes
        regexp: '^((?!.*cgroup_memory=1).+)$'
        line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
      tags:
        - mem_issue
        - raspberry

    - name: Ejecutar playbook de cada stack
      include_tasks:
        file: "stacks/containers/{{ item }}.yml"
        apply:
          tags: containers_up
      loop: "{{ stacks }}"
      when: item not in disabled_stacks
      tags:
        - containers_up

    - name: Detener servicios con Docker Compose en múltiples carpetas
      shell: "docker compose -f {{ ROOT_DATA_DIR }}/homelab-project/docker/{{ item }}/docker-compose.yml down"
      loop: "{{ stacks }}"
      when: item not in disabled_stacks
      tags:
        - containers_down

    - name: Ejecutar backup a S3
      import_tasks: "stacks/backup.yml"
      tags:
        - containers_backup

    - name: Restaurar desde S3
      import_tasks: "stacks/restore.yml"
      tags:
        - containers_restore
