---
- name: Desplegar contenedores en lab
  hosts: localhost
  tasks:
    - name: Crear red Docker traefik_net
      docker_network:
        name: traefik_net
        state: present
    - name: Detener servicios con Docker Compose en múltiples carpetas
      shell: "docker-compose -f {{ item }}/docker-compose.yml down"
      loop:
        - "{{ ROOT_DATA_DIR }}/homelab-project/docker/traefik"
        - "{{ ROOT_DATA_DIR }}/homelab-project/docker/portainer"
        - "{{ ROOT_DATA_DIR }}/homelab-project/docker/watchtower"
        - "{{ ROOT_DATA_DIR }}/homelab-project/docker/gitea"
        - "{{ ROOT_DATA_DIR }}/homelab-project/docker/monitoreo"
        - "{{ ROOT_DATA_DIR }}/homelab-project/docker/homarr"
      args:
        chdir: "{{ item }}"
      tags:
        - docker_compose_down
    - name: Ejecutar playbook de Traefik
      include_tasks: stacks/traefik-proxy.yml
    - name: Ejecutar playbook de Portainer
      include_tasks: stacks/portainer.yml
    - name: Ejecutar playbook de Watchtower
      include_tasks: stacks/watchtower.yml
    - name: Ejecutar playbook de Gitea
      include_tasks: stacks/gitea.yml
    - name: Ejecutar playbook de Monitoreo
      include_tasks: stacks/monitoreo.yml
    - name: Ejecutar playbook de Homarr
      include_tasks: stacks/homarr.yml
    - name: Ejecutar playbook de Navidrome
      include_tasks: stacks/navidrome.yml