---
- name: Desplegar contenedores en lab principal
  hosts: localhost
  become: yes
  vars:
    stacks:
      - traefik-proxy
      - portainer
      - watchtower
      - gitea
      - monitoreo
      - homarr
      - navidrome
      - artifactory
      - cloudbeaver
  tasks:
    - name: Agregar al grupo sudoers
      import_tasks: "stacks/docker.yml"
      tags:
        - init
    
    - name: Setup inicial
      import_tasks: "stacks/config.yml"
      tags:
        - init

    - name: Detener servicios con Docker Compose en múltiples carpetas
      shell: "docker-compose -f {{ ROOT_DATA_DIR }}/homelab-project/docker/{{ item }}/docker-compose.yml down"
      loop: "{{ stacks }}"
      tags:
        - down

    - name: Ejecutar playbook de cada stack
      include_tasks: "stacks/{{ item }}.yml"
      loop: "{{ stacks }}"
      tags:
        - up
