services:
  postgres:
    image: ${DOCKER_REGISTRY}/postgres:15.6-alpine
    container_name: artifactory-db
    user: "$UID:$GID"
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${ROOT_DATA_DIR}/artifactory/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - traefik_net
  artifactory:
    image: ${DOCKER_REGISTRY}/jfrog/artifactory-oss:${ARTIFACTORY_VERSION}
    container_name: artifactory
    user: "$UID:$GID"
    environment:
      - ENABLE_MIGRATION=y
      - JF_SHARED_DATABASE_TYPE=postgresql
      - JF_SHARED_DATABASE_USERNAME=${DB_USER}
      - JF_SHARED_DATABASE_PASSWORD=${DB_PASSWORD}
      - JF_SHARED_DATABASE_URL=jdbc:postgresql://artifactory-db:5432/artifactory
      - JF_SHARED_DATABASE_DRIVER=org.postgresql.Driver
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
    ports:
      - 8081:8081
    volumes:
      - ${ROOT_DATA_DIR}/artifactory/var:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    labels:
      # WATCHTOWER
      - com.centurylinklabs.watchtower.enable=true
      # TRAEFIK
      - "traefik.enable=true"
      - "traefik.http.routers.artifactory.rule=Host(`${ARTIFACTORY_DOMAIN}`)"
      - "traefik.http.routers.artifactory.entrypoints=websecure"
      - "traefik.http.routers.artifactory.tls.certresolver=cloudflare"
      - "traefik.http.services.artifactory.loadbalancer.server.port=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}"
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true