# stacks/cloudbeaver.yml

- name: Crear directorios para volúmenes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ROOT_DATA_DIR }}/cloudbeaver"

- name: Ejecutar Docker Compose
  community.docker.docker_compose_v2:
    project_src: ../docker/cloudbeaver
    state: present
  environment:
    ROOT_DATA_DIR: "{{ ROOT_DATA_DIR }}"
    TIMEZONE: "{{ TIMEZONE }}"
    CLOUDBEAVER_DOMAIN: "{{ CLOUDBEAVER_DOMAIN }}"
  register: result

- name: Mostrar resultado
  debug:
    msg: "{{ result }}"
