# stacks/config.yml

- name: Ejecutar script de alias de Git
  ansible.builtin.script: 
    cmd: ../docker/git/alias.sh

- name: Crear directorios base
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ANSIBLE_USER }}"
    group: "{{ ANSIBLE_USER }}"
  loop:
    - "~/repos"
    - "~/repos/personal"
    - "~/docker"
    - "~/documents"
