# Instalar Docker Compose
- name: Actualizar los paquetes APT
  apt:
    update_cache: yes

- name: Descargar Docker Compose
  become: yes
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x'

- name: Verificar que Docker Compose está instalado
  command: docker-compose --version
  register: docker_compose_version
  changed_when: false

- name: Mostrar versión de Docker Compose instalada
  debug:
    msg: "Docker Compose versión: {{ docker_compose_version.stdout }}"