# stacks/docker.yml

- name: Actualizar los paquetes APT
  apt:
    update_cache: yes

- name: Asegurarse de que el servicio Docker esté en ejecución
  service:
    name: docker
    state: started
    enabled: yes

- name: Añadir el usuario al grupo docker
  user:
    name: "{{ ANSIBLE_USER }}"
    groups: docker
    append: yes

- name: Verificar que Docker se puede ejecutar sin sudo
  command: docker --version
  register: docker_version
  changed_when: false

- name: Mostrar versión de Docker instalada
  debug:
    msg: "Docker versión: {{ docker_version.stdout }}"