# stacks/homarr.yml

- name: Crear directorios para volúmenes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ROOT_DATA_DIR }}/homarr/configs"
    - "{{ ROOT_DATA_DIR }}/homarr/icons"
    - "{{ ROOT_DATA_DIR }}/homarr/data"

- name: Copiar archivos de configuración
  copy:
    src: "../docker/homarr/config/{{ item }}"
    dest: "{{ ROOT_DATA_DIR }}/homarr/configs/{{ item }}"
  loop:
    - default.json

- name: Ejecutar Docker Compose
  community.docker.docker_compose_v2:
    project_src: ../docker/homarr
    state: present
  environment:
    ROOT_DATA_DIR: "{{ ROOT_DATA_DIR }}"
    TIMEZONE: "{{ TIMEZONE }}"
    HOMARR_DOMAIN: "{{ HOMARR_DOMAIN }}"
  register: result

- name: Mostrar resultado
  debug:
    msg: "{{ result }}"
