# stacks/m2.yml

- name: Crear directorio de montaje M.2
  become: yes
  file:
    path: "{{ storage_mountpoint }}"
    state: directory
    mode: '0755'

- name: Montar dispositivo M.2 por UUID
  become: yes
  ansible.posix.mount:
    path: "{{ storage_mountpoint }}"
    src: "UUID={{ storage_uuid }}"
    fstype: "{{ storage_fstype }}"
    opts: defaults
    state: mounted