# stacks/microbin.yml

- name: Ejecutar Docker Compose
  community.docker.docker_compose_v2:
    project_src: ../docker/microbin
    state: present
  environment:
    TIMEZONE: "{{ TIMEZONE }}"
    MICROBIN_ADMIN_USERNAME: "{{ MICROBIN_ADMIN_USERNAME }}"
    MICROBIN_ADMIN_PASSWORD: "{{ MICROBIN_ADMIN_PASSWORD }}"
    MICROBIN_DOMAIN: "{{ MICROBIN_DOMAIN }}"
  register: result

- name: Mostrar resultado
  debug:
    msg: "{{ result }}"