# stacks/gitea.yml

- name: Crear directorios para volúmenes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ROOT_DATA_DIR }}/portainer/data"

- name: Ejecutar Docker Compose
  docker_compose:
    project_src: ../docker/portainer
    state: present
  environment:
    ROOT_DATA_DIR: "{{ ROOT_DATA_DIR }}"
    TIMEZONE: "{{ TIMEZONE }}"
    PORTAINER_DOMAIN: "{{ PORTAINER_DOMAIN }}"
  register: result

- name: Mostrar resultado
  debug:
    msg: "{{ result }}"
