# stacks/traefik.yml

- name: Crear directorios para volúmenes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ROOT_DATA_DIR }}/watchtower/log"

- name: Ejecutar Docker Compose
  docker_compose:
    project_src: ../docker/traefik
    state: present
  environment:
    ROOT_DATA_DIR: "{{ ROOT_DATA_DIR }}"
    TRAEFIK_CLOUDFLARE_EMAIL: "{{ TRAEFIK_CLOUDFLARE_EMAIL }}"
    TRAEFIK_CLOUDFLARE_DNS_API_TOKEN: "{{ TRAEFIK_CLOUDFLARE_DNS_API_TOKEN }}"
    TRAEFIK_DOMAIN: "{{ TRAEFIK_DOMAIN }}"
  register: result

- name: Mostrar resultado
  debug:
    msg: "{{ result }}"
